package heven.greendaotest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import heven.greendaotest.Person;
import heven.greendaotest.Tree;

import heven.greendaotest.PersonDao;
import heven.greendaotest.TreeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig treeDaoConfig;

    private final PersonDao personDao;
    private final TreeDao treeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        treeDaoConfig = daoConfigMap.get(TreeDao.class).clone();
        treeDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        treeDao = new TreeDao(treeDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Tree.class, treeDao);
    }
    
    public void clear() {
        personDaoConfig.clearIdentityScope();
        treeDaoConfig.clearIdentityScope();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public TreeDao getTreeDao() {
        return treeDao;
    }

}
